# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: dark_blue # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 12 # column width relative to the terminal window
    min_width: 25 # minimum column width as number of characters
  comment:
    color: white
    width_percentage: 32
    min_width: 30
  snippet:
    color: grey

finder:
  command: fzf # equivalent to the --finder option
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

# cheats:
  # paths:
    # - /path/to/some/dir
    # - /path/to/another/dir
  # path: /path/to/some/dir # (DEPRECATED) equivalent to the --path option

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: fish # shell used for shell out. possible values: bash, zsh, dash, ...
  # finder_command: bash # similar, but for fzf's internals